### PR TITLE
WebView WPF Layout Issues

### PR DESCRIPTION
**Pull request by rjmurillo**
Issue: #

## PR Type
What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

WebView in WPF layouts does not function as expected:
- When initializing a WebView programmatically, a grey box is displayed instead of the WebView until the Window is resized
- When initializing a WebView within a columned layout, such as a Grid, a grey box is displayed instead of the WebView. Window resizing does not render the control.
- Diagnostic messages relating to HWND position have a formatting error

## What is the new behavior?
- **Ensure WebView is initialized prior to WindowPOS call**. During initialization the size of the control may not be correctly set causing a grey rect to be displayed. This is due to a timing issue with the dispatcher wherein the control has been resized by the visual layout system but has not yet finished initialization, causing the bounds to not be set. The call to update the render size has been moved to after the control is initialized to resolve this issue. It causes a noticeable layout event wherein the grey box is displayed then swapped for the actual control.
- **Reset horizontal pos during WPF WebView bounds update**. The vertical and horizontal coordinates are relative to the Window, not the containing UIElement. Given a Window with a Grid of only three columns, each 200px wide, the WebView set to Grid position 0,1 X value of 200, placing it in the third column of the Grid instead of the expected second column. There was already a hack in place to zero out the Y position of the location. This has been extended to the X position as well.
- **Fix DEBUG_LAYOUT messages for WPF WebView**. When writing the updated RECT the value displayed incorrectly as `oldBounds={x=371 y=0 width=371 height=F655}}` rather than `oldBounds={x=371 y=0 width=371 height=655}`

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current [supported SDKs](../readme.md#supported)
- [ ] Pull Request has been submitted to the documentation repository [instructions](..\contributing.md#docs). Link: 
- [ ] Sample in sample app has been added / updated (for bug fixes / features)
    - [ ] Icon has been created (if new sample) following the [Thumbnail Style Guide and templates](https://github.com/windows-toolkit/WindowsCommunityToolkit-design-assets)
- [ ] Tests for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Header has been added to all new source files (run *build/UpdateHeaders.bat*)
- [x] Contains **NO** breaking changes

## Other information
Issues originally found in 5.0.1 of WebView NuGet package on 1809 by @joshholmes (we can link his issue to this PR when available). Fix verified on RS4 1803 17134.345, RS5 1809 17763.134, and Insiders 1809 18290.1000.

### CODE REVIEW

**Comment by rjmurillo** [comment]
@joshholmes Can you verify your issue is resolved with the [artifacts from the PR](https://dev.azure.com/dotnet/696bc9fd-f160-4e97-a1bd-7cbbb3b58f66/_apis/build/builds/7213/artifacts?artifactName=Packages&api-version=5.0-preview.5&%24format=zip)?

**Comment by azchohfi** [comment]
@joshholmes Any updates?

**Comment by verelpode** [comment]
WPF layout issues still exist in `Microsoft.Toolkit.Wpf.UI.Controls.WebView` 6.0.0-preview7.  When the `WebView` is a descendant of `System.Windows.Controls.Viewbox`, and when the `WebView` is placed in a row in a `Grid` where the RowDefinition is `Height="*"` (star not auto), then the size of the WebView is incorrectly calculated.  Depending on the circumstances, the WebView becomes either too small or too large.  Sometimes the WebView becomes too large and is truncated (for example the vertical scrollbar is outside of the window and therefore cut off), whereas sometimes the WebView becomes too small and light gray fills the remaining space below and right of the WebView.

You might say it's my own fault for placing `WebView` as a descendant of `Viewbox`.  Yeah, I'm working on removing the `Viewbox`.   However, `System.Windows.Controls.WebBrowser` correctly calculates the size in exactly the same situation with the `Viewbox` and `Grid`.  I do realize that it's a bit odd to use Viewbox here, but the point is, `System.Windows.Controls.WebBrowser` handles it correctly anyway, whereas `Microsoft.Toolkit.Wpf.UI.Controls.WebView` does not.

So, if it's possible, maybe you could use some of the layout/sizing code in `System.Windows.Controls.WebBrowser`, because it works better than that in `Microsoft.Toolkit.Wpf.UI.Controls.WebView`.

I don't know how the WebView layout/size is being calculated currently, but presumably it should use the following members:
```
System.Windows.UIElement.TranslatePoint(System.Windows.Point, System.Windows.UIElement)
System.Windows.UIElement.LayoutUpdated
System.Windows.FrameworkElement.SizeChanged
```
and yes I should stop placing `WebView` as a descendant of `Viewbox`.

**Comment by rjmurillo** [comment]
@verelpode Can you verify your scenario with this patch?

@liminzhu FYI

**Comment by verelpode** [comment]
@rjmurillo I tested it today with 6.0.0-preview7.1 and it is still cut off.  I tested it with [https://outlook.live.com/owa/](https://outlook.live.com/owa/) .  Firstly, here is a screenshot _without_ `Viewbox` -- note the scrollbar -- all good:
image

Following is a screenshot when the `WebView` is a descendant of `System.Windows.Controls.Viewbox` with `Viewbox.Stretch = Uniform;`.   The scrollbar is cut off (I did move the mouse because the scrollbar auto-hides, but no scrollbar appears;  the scrollbar is offscreen).
image

I realize that the Outlook webpage may be affected by sizing-sensitive EcmaScript inside the webpage -- some EcmaScript that detects the web "window" size and modifies the webpage to suit the smaller or larger "window" size.  Therefore, in order to eliminate EcmaScript from the equation, I also tested with [http://www.example.com](http://www.example.com) .  As you can see following, it is cut off in the same manner as the Outlook webpage, and likewise the scrollbar is cut off.
image

Just to confirm/clarify, although the webpage/content inside the WebView is not scaled in accordance with the ancestor Viewbox, I don't see this as a problem.  I only expected ViewBox's scaling to be correctly applied to the effective/runtime **bounds** of the WebView's HWND.  I don't expect the content inside the WebView to be shrunk or expanded according to the ancestor Viewbox.   Please tell me if my expectation here is incorrect.   If there is a plan to change this behavior in future, I would especially appreciate hearing about it now.

To explain the oddity of using Viewbox with WebView:  Although I'm working on eliminating this usage of Viewbox, it's not easy to do because the Viewbox is needed for elements other than the WebView, and it's not easy to separate the WebView from those elements that need the Viewbox.  That's why the WebView ended up as a descendant of a Viewbox.  But actually, even after I remove this usage of Viewbox, it will _still_ be possible for our users to configure our software in such a way that WebView again becomes a descendant of a Viewbox.  So it would be great to have this scenario supported, as does `System.Windows.Controls.WebBrowser`.

By the way, thanks very much for bringing WebView to WPF!  This is a lifesaver for us.  An "all or nothing" switch to UWP was difficult to achieve in the case of our enterprise software.  But now, thanks to WebView-for-WPF and XAML Islands, the job can be progressively completed in stages, and also tested and deployed in stages, and this is much more feasible and practical than the previous "all or nothing" requirement.

**Comment by rjmurillo** [comment]
@verelpode Since the patch is not integrated into a shipping branch it won't be in a binary. What I was asking was for you to get the source, apply this patch, compile, and test your scenario to see if this solves your problem.

I suspect the patch will correct the problem--the offset was incorrectly calculated when the webview was nested in certain scenarios and the changes correct the position.

**Comment by verelpode** [comment]
@rjmurillo 
Oh OK, so today's release of 6.0.0-preview7.1 was only coincidence.  OK, now I tested with your patch, and I also tested commenting-out and uncommenting the line in your patch where you do `x = 0;`, and either way, the rendered result seemed the same in my test app, and the webpage + scrollbar was still cut off.

The thing is, the `WebView.UpdateBounds(double x, double y, double width, double height)` method **is not invoked anyway** when I (as user) resize the ancestor WPF window that contains the Viewbox that contains the WebView.  So it doesn't make any difference what is done in `UpdateBounds` because it's not executed anyway.  It's executed when the `WebView` is created/attached etc, but not executed when the user resizes the ancestor WPF window.   

So, as a quick experiment, I forced `WebView.UpdateBounds` to be executed by subscribing to the `LayoutUpdated` event:
```
protected WebViewHost()
{
    ...
    SizeChanged += OnSizeChanged;
    LayoutUpdated += OnTestLayoutUpdated;
    ...
}
private void OnTestLayoutUpdated(object sender, EventArgs e)
{
    UpdateSize(new Size(this.ActualWidth, this.ActualHeight));
}
```

So then `UpdateBounds` was executed via `WebViewHost.UpdateSize` via event `LayoutUpdated`, but the rendered result appeared unchanged.  Still cut off.  Thus _maybe_ the HWND size is actually calculated _correctly_ but the web content inside the HWND doesn't know the HWND size changed, and renders it with the wrong width and height, even though the HWND size changed.  What do you think?

**Comment by verelpode** [comment]
I fixed it.  You need to override `HwndHost.OnWindowPositionChanged` and invoke `WebViewHost.UpdateSize`, like this:

```
public abstract class WebViewHost : HwndHost
{
	...
	protected override void OnWindowPositionChanged(Rect rcBoundingBox)
	{
		base.OnWindowPositionChanged(rcBoundingBox);
		UpdateSize(rcBoundingBox.Size);
	}
	...
}
```

With this fix, the webpage is not cut off anymore.  HOWEVER, although it works, I haven't properly thought this through.  Quite possibly this fix isn't 100% correct, despite appearing to work successfully.

**Comment by verelpode** [comment]
The implementation of `OnWindowPositionChanged` in my previous message incorrectly applies DpiScale **twice**, because `OnWindowPositionChanged` receives a Rect **already** scaled for DPI.  Thus following is a better implementation, although still not guaranteed to be 100% correct.

```
public abstract class WebViewHost : HwndHost
{
	...
	protected override void OnWindowPositionChanged(Rect rcBoundingBox)
	{
		base.OnWindowPositionChanged(rcBoundingBox);
		// rcBoundingBox is already scaled for DPI.  Do not multiply it by WebViewHost.DpiScale.
		UpdateSize(rcBoundingBox.Size, dpiScaleApplied: true);
	}
	...
	protected virtual void UpdateSize(Size size, bool dpiScaleApplied = false)
	{
		var rect = new Rect( VisualOffset.X, VisualOffset.Y, size.Width, size.Height);
		UpdateBounds(rect, dpiScaleApplied);
	}

	protected abstract void UpdateBounds(Rect bounds, bool dpiScaleApplied);
	...
} // class WebViewHost

public sealed partial class WebView : WebViewHost, IWebView, IWebViewCompatible
{
	...
	protected override void UpdateBounds(Rect bounds, bool dpiScaleApplied)
	{
		UpdateBounds(bounds.X, bounds.Y, bounds.Width, bounds.Height, dpiScaleApplied);
	}

	private void UpdateBounds(double x, double y, double width, double height, bool dpiScaleApplied)
	{
		...
		if (!dpiScaleApplied)	// if DpiScale not already applied
		{
			width *= DpiScale.DpiScaleX;
			height *= DpiScale.DpiScaleY;
		}
		x = 0;
		y = 0;
		...
		if (WebViewControlInitialized)
		{
			var rect = new windows.Foundation.Rect(new Point(x, y), new Size(width, height));
			_webViewControl?.UpdateBounds(rect);
		}
		...
	}
	...
} // class WebView
```

**Comment by marb2000** [comment]
Given there is no activity of this PR, can we close it?

**Comment by michael-hawker** [comment]
Good point @marb2000, folks should be testing out WebView2, so I think we can close this. Thanks for bumping the discussion.

**Pull request closed without merging**
