### PR TITLE
Add wrapper for TextBox and RichEditBox

### PR DESCRIPTION
**Pull request by pengzh0928**
Issue: #2 

## PR Type
What kind of change does this PR introduce?

 Feature

Sample app changes

## What is the current behavior?

There's no TextBox and RichEditBox wrapper control and sample code in XamlIsland.

## What is the new behavior?
Create TextBox and RichEditBox wrapper control, also add samples in the sample APp

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](../readme.md#supported)
- [ ] Pull Request has been submitted to the documentation repository [instructions](..\contributing.md#docs). Link: 
- [x] Sample in sample app has been added / updated (for bug fixes / features)
    - [ ] Icon has been created (if new sample) following the [Thumbnail Style Guide and templates](https://github.com/windows-toolkit/WindowsCommunityToolkit-design-assets)
- [ ] Tests for the changes have been added (for bug fixes / features) (if applicable)
- [x] Header has been added to all new source files (run *build/UpdateHeaders.bat*)
- [x] Contains **NO** breaking changes

### CODE REVIEW

**Comment by gegao18** [comment]
I'm not sure this is the right model for the sample. I think we want one DesktopWindowXamlSource hosting an entire tree of Xaml controls, rather than wrapping each individual Xaml control in its own DesktopWindowXamlSource.

**Comment by DJDGSFTX** [comment]
> I'm not sure this is the right model for the sample. I think we want one DesktopWindowXamlSource hosting an entire tree of Xaml controls, rather than wrapping each individual Xaml control in its own DesktopWindowXamlSource.
> 
> I have a PR that I'm about to send out which removes the Microsoft.Toolkit.Forms.UI.Controls project entirely and just puts a WindowsXamlHost directly in the WPF TabControl. Then we can build a Windows.UI.Xaml StackPanel and put all sorts of controls inside.

Hi, George @gegao18. Your opinion is make sense.  Where could I find your PR?

**Comment by DJDGSFTX** [comment]
Oh, I find it. https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/pull/15

One more question, which branch I should check-in? Seems like I should use rel/6.0.0 or rel/6.0.0-preview-3 or others?

**Comment by marb2000** [comment]
Thanks for the PR. Unfortunately, we are decided no longer adding more .NET wrappers for system UWP controls.

**Pull request closed without merging**
