### PR TITLE
Enable Control Flow Guard

### LINKED ISSUE #263: Cannot load Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication if Control Flow Guard is enforced
## Steps to Reproduce
1. Create an application enabling Control Flow Guard enforcement by adding the following in the entry point:
   ```cpp
   PROCESS_MITIGATION_CONTROL_FLOW_GUARD_POLICY cfg_policy;
   GetProcessMitigationPolicy(GetCurrentProcess(), ProcessControlFlowGuardPolicy, &cfg_policy, sizeof(cfg_policy));
   cfg_policy.StrictMode = true;
   SetProcessMitigationPolicy(ProcessControlFlowGuardPolicy, &cfg_policy, sizeof(cfg_policy));
   ```
2. Try to create an instance of `Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication` (or have it implicitly happen by creating an instance of a type which derives from it)
3. Add the required `activatableClass` and `maxversiontested` entries to your app manifest.
4. Enable Control Flow Guard in Visual Studio project settings
5. Build and run a release configuration.
6. See exception get thrown, with the message `The specified image file was blocked from loading because it does not enable a feature required by the process: Control Flow Guard.`

## Expected behavior
An exception doesn't get thrown, and the type gets created correctly.

## Environment

```
NuGet Package(s):
 - Microsoft.Toolkit.Win32.UI.XamlApplication (v6.0.1)
 - Microsoft.VCRTForwarders.140 (v1.0.6)
 - Microsoft.Windows.CppWinRT (v2.0.200508.4)

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [x] Insider Build (build number: 19041)

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] May 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2019 (version: ) 
- [x] 2019 Preview (version: 16.6.0 Preview 6.0)

```

## Additional context
This code, with the instructions above, suffices to reproduce it.
```cpp
#include <iostream>
#include <winrt/base.h>
#include <winrt/Microsoft.Toolkit.Win32.UI.XamlHost.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <Windows.h>

int main() try
{
    PROCESS_MITIGATION_CONTROL_FLOW_GUARD_POLICY cfg_policy;
    GetProcessMitigationPolicy(GetCurrentProcess(), ProcessControlFlowGuardPolicy, &cfg_policy, sizeof(cfg_policy));
    cfg_policy.StrictMode = true;
    SetProcessMitigationPolicy(ProcessControlFlowGuardPolicy, &cfg_policy, sizeof(cfg_policy));
    
    winrt::init_apartment(winrt::apartment_type::single_threaded);
    winrt::Microsoft::Toolkit::Win32::UI::XamlHost::XamlApplication app(winrt::param::vector<winrt::Windows::UI::Xaml::Markup::IXamlMetadataProvider>{});
}
catch (const winrt::hresult_error &err)
{
    std::wcout << err.message().c_str();
}
```

### PR DESCRIPTION
**Pull request by sylveon**
Fixes #263

## PR Type
What kind of change does this PR introduce?

- Bugfix
- Build or CI related changes

## What is the current behavior?
The DLL fails to load if strict Control Flow Guard is enforced

## What is the new behavior?
The DLL uses Control Flow Guard and does not fail to load

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tested code with current [supported SDKs](../readme.md#supported)
- [x] Contains **NO** breaking changes

### CODE REVIEW

**Comment by sylveon** [comment]
Welp, apparently this doesn't solve the issue, will need to investigate

**Comment by sylveon** [comment]
Found the issue... VCRT forwarders aren't marked as CFG-aware

**Comment by sylveon** [comment]
This works if combined with #251

**Comment by marb2000** [comment]
I've concerns about adding the Control Flow Guard (CFG) directive because it's a scenario out of the test matrix, and we need to validate all the top scenarios. 

@sylveon, did you tested the [XAML Islands Samples](https://github.com/microsoft/Xaml-Islands-Samples) with this configuration? This is the minimum bar.

**Comment by sylveon** [comment]
Well, my application works with this and anything else that is broken by CFG is supposed to be a compiler bug. I checked anyways, and here's a build of `NativeXamlIslands.sln` running fine with a CFG-enabled XamlHost DLL

image

**Comment by marb2000** [comment]
This is cool 😊. What about the WPF and WinForms samples? We need to make sure that we don't break other scenarios.

By the way, the C++ sample we did is awful. It hurts my eyes every time I run it.

**Comment by sylveon** [comment]
image

image

**Comment by marb2000** [comment]
Thanks so much @sylveon. I'm testing this on my machine as well, before approving the PR.

**Pull request merged**
